### ISSUE TITLE
Error occurs for LBA_SIZE 4096

### ISSUE THREAD

**Issue by hopoic** [n0fate/raw#1]
Dear n0fate,

I tried to parse GPT of OnePlus5 device.

OnePlus5:/dev/block/bootdevice/by-name # dd if=/dev/block/sde of=/sdcard/sde_gpt.img bs=512 count=48

[sde_gpt.tar.gz](https://github.com/n0fate/raw/files/1464386/sde_gpt.tar.gz)

**I changed LBA_SIZE to 4096 and run, then error occurs:**
$ python gpt_parser.py sde_gpt.img
Traceback (most recent call last):
  File "gpt_parser.py", line 456, in <module>
    main()
  File "gpt_parser.py", line 419, in main
    gpt_header, crc32_header_value, gpt_buf = get_gpt_header(f, fbuf, PRIMARY_GPT_LBA)
  File "gpt_parser.py", line 56, in get_gpt_header
    gpt_header = struct.unpack(GPT_HEADER_FORMAT, fbuf)
struct.error: unpack requires a string argument of length 512

**Fixed with using first 512 bytes of fbuf:**
gpt_parser.py line 56
`    gpt_header = struct.unpack(GPT_HEADER_FORMAT, fbuf[0:512])`

Thank you,

**Comment by n0fate** [comment]
Thank you. I fixed this. ;-)
